backend:
  name: git-gateway
  branch: main

media_folder: "."
public_folder: "/"

locale: "es"

collections:
  - name: "catalogos"
    label: "Catálogos"
    label_singular: "Catálogo"
    files:
      - name: "catalogo-distribuidor"
        label: "Catálogo Distribuidor"
        file: "catalogo-distribuidor.md"
        fields:
          - { label: "PDF", name: "pdf", widget: "file", media_folder: "/", public_folder: "/" }

      - name: "catalogo-cliente-final"
        label: "Catálogo Cliente Final"
        file: "catalogo-cliente-final.md"
        fields:
          - { label: "PDF", name: "pdf", widget: "file", media_folder: "/", public_folder: "/" }

      - name: "catalogo-regimen-simplificado"
        label: "Catálogo Régimen Simplificado"
        file: "catalogo-regimen-simplificado.md"
        fields:
          - { label: "PDF", name: "pdf", widget: "file", media_folder: "/", public_folder: "/" }

      - name: "catalogo-sin-precios"
        label: "Catálogo Sin Precios"
        file: "catalogo-sin-precios.md"
        fields:
          - { label: "PDF", name: "pdf", widget: "file", media_folder: "/", public_folder: "/" }

      - name: "catalogo-sin-precios-regimen-simplificado"
        label: "Catálogo Sin Precios Régimen Simplificado"
        file: "catalogo-sin-precios-regimen-simplificado.md"
        fields:
          - { label: "PDF", name: "pdf", widget: "file", media_folder: "/", public_folder: "/" }