backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "es"

collections:
  - name: "catalogos"
    label: "Catalogos"
    label_singular: "Catalogo"
    files:
      - name: "catalogo-distribuidor"
        label: "Catalogo Distribuidor"
        file: "catalogo-distribuidor.md"
        fields:
          - { label: "Titulo", name: "title", widget: "string", default: "Catalogo Distribuidor" }
          - { label: "PDF", name: "pdf", widget: "file", media_library: { config: { multiple: false } } }
      - name: "catalogo-cliente-final"
        label: "Catalogo Cliente Final"
        file: "catalogo-cliente-final.md"
        fields:
          - { label: "Titulo", name: "title", widget: "string", default: "Catalogo Cliente Final" }
          - { label: "PDF", name: "pdf", widget: "file", media_library: { config: { multiple: false } } }
      - name: "catalogo-regimen-simplificado"
        label: "Catalogo Regimen Simplificado"
        file: "catalogo-regimen-simplificado.md"
        fields:
          - { label: "Titulo", name: "title", widget: "string", default: "Catalogo Regimen Simplificado" }
          - { label: "PDF", name: "pdf", widget: "file", media_library: { config: { multiple: false } } }
      - name: "catalogo-sin-precios"
        label: "Catalogo Sin Precios"
        file: "catalogo-sin-precios.md"
        fields:
          - { label: "Titulo", name: "title", widget: "string", default: "Catalogo Sin Precios" }
          - { label: "PDF", name: "pdf", widget: "file", media_library: { config: { multiple: false } } }
      - name: "catalogo-sin-precios-regimen-simplificado"
        label: "Catalogo Sin Precios Regimen Simplificado"
        file: "catalogo-sin-precios-regimen-simplificado.md"
        fields:
          - { label: "Titulo", name: "title", widget: "string", default: "Catalogo Sin Precios Regimen Simplificado" }
          - { label: "PDF", name: "pdf", widget: "file", media_library: { config: { multiple: false } } }
